### ISSUE TITLE
Revert T3 Static Artillery to the FAF Cost.

### ISSUE THREAD

**Issue by Azraeel** [Azraeel/LOUD-Community-Edition#10]

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by Azraeel** [comment]
Completed in https://github.com/Azraeel/LOUD-Community-Edition/commit/3b9c8e26eefbac9046488dec34b73f6063fd56db
