### ISSUE TITLE
Remove spawn waves

### ISSUE THREAD

**Issue by Kami-Interface** [Azraeel/LOUD-Community-Edition#22]

**Comment by loudpatches** [comment]
couple of options:

 intercept here https://github.com/LOUD-Project/Git-LOUD/blob/master/gamedata/lua/lua/AI/aiutilities.lua#L740
or turn this into a no-op 
https://github.com/LOUD-Project/Git-LOUD/blob/master/gamedata/lua/lua/loudutilities.lua#L599
could afford some flexibility, if AI can't function without the crutch, maybe this is configurable in lobby settings or something (could play with magnitude / delay as well).  Simplest is to just bypass it though.
